// How Does Java Programming Language Work?

/*Start by writing your Java code using a text editor or an integrated development environment (IDE). Java code is usually saved with a ‘.java’ extension.
  In this case we have Learn.java file. */

// Main class
public class Learn {

  // Main driver method
  public static void main(String[] args) {

    // Print statement
    System.out.println("Hello World!");
    
    /*Once you have written your Java code, the next step is to compile it. 
    Compilation is the process of converting human-readable Java code into bytecode, 
    which is a low-level representation of the code that can be executed only by the Java Virtual Machine (JVM).*/
  }    
}

/* The computer’s hardware does not execute the generated bytecode directly. 
Instead, it runs on the Java Virtual Machine (JVM). 
The JVM is platform-independent, allowing Java programs to run on any machine with a compatible JVM.*/
  

